name: CI
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run-code-quality:
        description: 'Check code quality?'
        required: false
        type: boolean
        default: false

concurrency:
  group: "${{ github.ref }}-ci"
  cancel-in-progress: true

jobs:
  markup-lint:
    name: Markup
    uses: devpro/github-workflow-parts/.github/workflows/reusable-markup-lint.yml@359427548fbdfbc8af19b17d6b0a41fa20f51a37

  code-quality:
    name: Code
    if: github.event_name != 'workflow_dispatch' || inputs.run-code-quality
    uses: devpro/github-workflow-parts/.github/workflows/reusable-dotnet-quality.yml@359427548fbdfbc8af19b17d6b0a41fa20f51a37
    with:
      operating-system: windows-latest
